#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'steam'
require 'bundler'

Bundler.setup :default

Steam.connect username: "mkroman", password: "9qQn5ZYvCNei88QSud7V" do
  log.info "Steam #{Steam::Version}" ^ :bold
  log.info "Connecting to steam servers…"
end
