#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'steam'
require 'bundler'

Bundler.setup :default

Steam.connect username: "my-account", password: "my-password" do
  log.info "Steam #{Steam::Version}" ^ :bold
  log.info "Connecting to steam servers…"
end
